config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "top#main"
  get 'top/main'
  resources :products
  resources :cart_items, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    validates :qty,
        presence: true,
        numericality: { only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name,
        presence: true
    validates :price,
        presence: true,
        numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
    private
        def current_cart
            if session[:cart_id]
              cart = Cart.find(session[:cart_id])
            else
               cart = Cart.create
               session[:cart_id] = cart.id
            end
            cart
        end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    
  def new
    @cart_item = CartItem.new
  end
  
  def create
    c = CartItem.new(
        qty: params[:cart_item][:qty], 
        product_id: params[:cart_item][:product_id], 
        cart_id: current_cart.id
    )
    c.save
    flash[:notice] = 'カートに追加しました。'
    redirect_to cart_path(current_cart.id)
  end
  
  def destroy
    CartItem.find(params[:id]).destroy
    flash[:notice] = 'カートから削除しました。'
    redirect_to cart_path(current_cart.id)
  end
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    
    def show
        @cart_items = CartItem.where(cart_id: current_cart.id)
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    pd = Product.new(name: params[:product][:name], price: params[:product][:price])
    pd.save
    flash[:notice] = '商品を追加しました。'
    redirect_to root_path
  end
  
  def destroy
    Product.find(params[:id]).destroy
    flash[:notice] = '商品を削除しました。'
    redirect_to root_path
  end
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    
    def main
        redirect_to products_path
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/new.html.erb
<h1>カート追加</h1>

<%= form_with model: @cart_item, url: cart_items_path do |f| %>
    <p>
        <%= f.label :name, '商品名称' %>：<%= Product.find(params[:product_id]).name %>
    </p>
    <p>
        <%= f.label :price, '商品価格' %>：<%= Product.find(params[:product_id]).price %>円
    </p>
    <p>
        <%= f.label :qty, '数量' %>：<%= f.text_field :qty %>点
    </p>
    <%= f.hidden_field :product_id, value: params[:product_id] %>
    <%= f.submit '商品を登録する' %>
<% end %>

<p><%= link_to "商品一覧に戻る", root_path %></p>

app/views/carts/show.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

<h1>カート</h1>

<% all = 0 %>
<% @cart_items.each do |ci| %>
  <p>商品<%= ci.id %>（<%= Product.find(ci.product_id).name %>、<%= Product.find(ci.product_id).price %>円、<%= ci.qty %>点）
  <%= link_to 'カートから削除', cart_item_path(ci), data: {turbo_method: :delete} %></p>
  <% all += Product.find(ci.product_id).price * ci.qty %>
<% end %>
<br>
<p>合計金額<%= all %>円</p>

<p><%= link_to "商品一覧に戻る", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

<h1>商品一覧</h1>

<% @products.each do |pd| %>
  <p>商品<%= pd.id %>（<%= pd.name %>、<%= pd.price %>円）
  <%= link_to '削除', product_path(pd), data: {turbo_method: :delete} %>
  <%= link_to 'カート追加', new_cart_item_path(product_id: pd.id) %></p>
<% end %>

<p><%= link_to "商品を追加する", new_product_path %></p>
<p><%= link_to "カートを見る", cart_path(current_cart.id) %></p>

app/views/products/new.html.erb
<h1>商品追加</h1>

<%= form_with model: @product do |f| %>
  <p>
    <%= f.label :name, '商品名称' %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price, '商品価格' %>
    <%= f.text_field :price %>円
  </p>
  <%= f.submit '追加' %>
<% end %>

<p><%= link_to "商品一覧に戻る", root_path %></p>